-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here

-- function ColorMyPencil(color)
--   color = color or "flow"
--   vim.cmd.colorscheme(color)
--
--   vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
--   vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
--   vim.api.nvim_set_hl(0, "NormalNC", { bg = "none" })
--   vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = "none" })
--   vim.api.nvim_set_hl(0, "NvimTreeNormalNC", { bg = "none" })
--   vim.api.nvim_set_hl(0, "NeoTreeNormal", { bg = "none" })
--   vim.api.nvim_set_hl(0, "NeoTreeNormalNC", { bg = "none" })
-- end
--
-- ColorMyPencil()

-- vim.opt.spelllang = "en_us" -- Set the language for spell checking
-- vim.opt.spell = true -- Enable spell checking
-- vim.opt.spelloptions = "camel" -- Enable camelCase spell checking
--
-- vim.opt.spellfile = vim.fn.stdpath("config") .. "/spell/en.utf-8.add"
-- vim.opt.spelllang = "en_us"
-- vim.opt.spelloptions = "camel"
